version: '3.8'

services:
  radio-app:
    build:
      context: .
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: radio-dedalos-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - radio-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: radio-mysql-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - radio-network

  nginx:
    image: nginx:alpine
    container_name: radio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - radio-network
    depends_on:
      - radio-app

networks:
  radio-network:
    driver: bridge

volumes:
  mysql-data: